name: Build Firmware

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization Environment
      run: |
        sudo apt-get update
        sudo apt-get install build-essential asciidoc binutils \
        bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip \
        zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs \
        git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo \
        libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf \
        automake libtool autopoint device-tree-compiler libpam0g-dev \
        libidn2-0-dev attr libpcre2-dev libexpat1-dev \
        libssh2-1-dev libgnutls-dev libldap2-dev libcap-dev liblzma-dev \
        libjansson-dev libpng-dev libupnp-dev \
        libgd-dev bc lm-sensors libtirpc-dev \
        libavahi-client-dev libarchive-dev mkisofs -y

    - name: Clone OpenWrt Project
      run: |
        git clone https://github.com/openwrt/openwrt.git ./openwrt
        # cd ./openwrt
        # git checkout -b v18.06.4

    - name: Update feeds
      working-directory: ./openwrt
      run: |
        echo "src-git extra https://github.com/buxiaomo/openwrt-extra.git" >> feeds.conf.default
        echo "src-git ssr https://github.com/buxiaomo/luci-app-ssr-plus.git" >> feeds.conf.default
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Make Config
      working-directory: ./openwrt
      run: |
        cp -fr ../config ./.config
        make defconfig
        make oldconfig

    - name: Custom Settings
      working-directory: ./openwrt
      run: |
        # NTP
        echo "Settinng NTP Server"
        sed -i "s/0.openwrt.pool.ntp.org/ntp1.aliyun.com/g" ./package/base-files/files/bin/config_generate
        sed -i "s/1.openwrt.pool.ntp.org/ntp2.aliyun.com/g" ./package/base-files/files/bin/config_generate
        sed -i "s/2.openwrt.pool.ntp.org/ntp3.aliyun.com/g" ./package/base-files/files/bin/config_generate
        sed -i "s/3.openwrt.pool.ntp.org/ntp4.aliyun.com/g" ./package/base-files/files/bin/config_generate

        # Timezone
        echo "Settinng Timezone"
        sed -i "s/UTC/CST-8/g" ./package/base-files/files/bin/config_generate
        sed -i "/CST-8/a set system.@system[-1].zonename='Asia/Shanghai'" ./package/base-files/files/bin/config_generate

    - name: Download package source code
      working-directory: ./openwrt
      run: |
        make download -j$(nproc) V=s

    - name: Compile firmware
      working-directory: ./openwrt
      run: |
        echo -e "$(nproc) thread build."
        make -j$(nproc) V=s

    - name : Upload Artifact
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt-GL-MiFi
        path: openwrt/bin/targets/ar71xx/generic/