name: Build Firmware

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
    - name: Test
      run: |
        ls -lah

    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization Environment
      run: |
        sudo apt-get update
        sudo apt-get -y install build-essential asciidoc binutils \
        bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip \
        zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs \
        git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo \
        libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf \
        automake libtool autopoint device-tree-compiler libpam0g-dev \
        libidn2-0-dev attr libpcre2-dev libexpat1-dev \
        libssh2-1-dev libgnutls-dev libldap2-dev libcap-dev liblzma-dev \
        libjansson-dev libpng-dev libupnp-dev \
        libgd-dev bc lm-sensors libtirpc-dev \
        libavahi-client-dev libarchive-dev -y

    - name: Clone Lede Project
      run: git clone https://github.com/coolsnowwolf/lede.git ./lede

    - name: Using Openwrt Project Setting
      run: wget https://raw.githubusercontent.com/openwrt/openwrt/master/include/target.mk -O ./include/target.mk
      working-directory: ./lede

    - name: Setting GL-MiFi Menuconfig
      run: |
        cp -fr lede.config ./lede/.config
        make defconfig
        make oldconfig

    - name: Download Package
      run: make download -j8 V=s
      working-directory: ./lede

    - name: Build
      run: echo -e "$(nproc) thread build." ; make -j$(nproc) V=s
      working-directory: ./lede

    - name : Upload Artifact
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt-GL-MiFi
        path: lede/bin/targets/ar71xx/generic/