name: Test Firmware

on: [push]

# on: 
#   release:
#     types: [published]
#   push:
#     branches: 
#       - master
#     paths:
#       - 'config'
#       - 'files'
#       - 'feeds.conf.default'
#   schedule:
#     - cron: 0 2 * * 1-5

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      run: |
        sudo apt-get update
        sudo apt-get install git -y

    - name: Test command
      run: |
        HOME_DIR=`pwd`
        mkdir -p ${HOME_DIR}/tmp
        ls -ls
        echo "------------"        
        touch ${HOME_DIR}/tmp/aaa
        ls ${HOME_DIR}/tmp