name: Test Firmware

on: [push]

# on: 
#   release:
#     types: [published]
#   push:
#     branches: 
#       - master
#     paths:
#       - 'config'
#       - 'files'
#       - 'feeds.conf.default'
#   schedule:
#     - cron: 0 2 * * 1-5

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      run: |
        sudo apt-get update
        sudo apt-get install git -y

    - name: Test command
      run: |
        HOME_DIR=`pwd`
        echo "${HOME_DIR}"
        echo "--------------------------------"
        mkdir -p ${HOME_DIR}/output/firmware
        echo "--------------------------------"
        ls -l
        mkdir -p openwrt/bin/targets/a/b/packages
        touch  openwrt/bin/targets/a/b/packages/aaa
        touch  openwrt/bin/targets/a/b/fff
        echo "--------------------------------"
        cd openwrt/bin/targets/*/*
        mv ./packages/* ${HOME_DIR}/output/
        rm -rf packages
        mv * ${HOME_DIR}/output/firmware
        echo "--------------------------------"
        ls -l ${HOME_DIR}/output/firmware ${HOME_DIR}/output/packages