name: Test Firmware

on: [push]

# on: 
#   release:
#     types: [published]
#   push:
#     branches: 
#       - master
#     paths:
#       - 'config'
#       - 'files'
#       - 'feeds.conf.default'
#   schedule:
#     - cron: 0 2 * * 1-5

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      run: |
        sudo apt-get update
        sudo apt-get install git -y

    - name: Test command
      run: |
        mkdir tmp
        echo "Home ${HOME}"
        echo "File list 1"
        ls
        git clone https://github.com/openwrt/openwrt.git ./openwrt
        echo "File list 2"
        ls
        echo "mkdir ${HOME}/output/firmware"
        mkdir -p ${HOME}/output/firmware
        echo "File List 3"
        ls 